dataloader:
  data_name: cifar100
  batch_size: 64
teacher_model:
  model_name: resnet18
optimizer:
  opt_name: sgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0005
trainer:
  epochs: 240
  seed: 42
logging:
  framework_name: wandb
  project_name: knowledge-distillation-cifar100