dataloader:
  data_name: imagenet
  batch_size: 512
  num_workers: 32
teacher_model:
  model_name: resnet18
student_model:
  model_name: resnet18
optimizer:
  opt_name: sgd
  lr: 0.2
  momentum: 0.9
  weight_decay: 0.0001
trainer:
  epochs: 100
  seed: 42
logging:
  framework_name: wandb
  project_name: knowledge-distillation-cifar100